In [5]:

import numpy as np
from pyDatalog import pyDatalog
from pyDatalog import pyEngine

array1 = np.array([[0, .2, .7, .8 ], [0, .3, .7, .5], [.5, .5, .5, .5], [.7, .4, .4, .6 ], [.7, .7, .3, .3]])

array2 = np.array([[0, .2, .7, .8 ], [0, .3, .7, .5], [.5, .5, .5, .5], [.7, .4, .4, .6 ], [.7, .7, .3, .3]])


print("Колдуны")
print(arr1)
print("\n")
print("Волшебники")
print(arr2)
print("\n")

matrix = []
for i in array1:
    for j in array2:
        matrix.append(max(np.multiply(i, j)))


print("Колдуны и Волшебники")
print(matrix)

Колдуны
[[ 0.   0.2  0.7  0.8]
 [ 0.   0.3  0.7  0.5]
 [ 0.5  0.5  0.5  0.5]
 [ 0.7  0.4  0.4  0.6]
 [ 0.7  0.7  0.3  0.3]]


Волшебники
[[ 0.   0.3  0.3  0.7  0. ]
 [ 0.3  0.1  0.7  0.3  0.8]
 [ 0.8  0.6  0.5  0.4  0.3]
 [ 0.8  0.8  0.5  0.6  0.2]]


Колдуны и Волшебники
[0.64000000000000012, 0.48999999999999994, 0.40000000000000002, 0.47999999999999998, 0.23999999999999999, 0.48999999999999994, 0.48999999999999994, 0.34999999999999998, 0.29999999999999999, 0.20999999999999999, 0.40000000000000002, 0.34999999999999998, 0.25, 0.34999999999999998, 0.34999999999999998, 0.47999999999999998, 0.29999999999999999, 0.34999999999999998, 0.48999999999999994, 0.48999999999999994, 0.23999999999999999, 0.20999999999999999, 0.34999999999999998, 0.48999999999999994, 0.48999999999999994]
